export const GNSS_DEGREES_PRECISION_NUMBER_OF_DECIMAL_PLACES = 7;
export const ALTITUDE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 2;
export const DISTANCE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 1;
export const SPEED_PRECISION_NUMBER_OF_DECIMAL_PLACES = 2;
export const HEART_RATE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 1;
export const CADENCE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 1;
export const POWER_PRECISION_NUMBER_OF_DECIMAL_PLACES = 1;
export const TEMPERATURE_PRECISION_NUMBER_OF_DECIMAL_PLACES = 2;
