export const ImporterSuuntoDeviceNames: { [index: string]: string } = {
  Athens: '0',
  Paris: '1',
  Berlin: '2',
  Tokyo: '3',
  Rome: '4',
  Monza: '5',
  Moscow: '6',
  Kyoto: '7',
  Lisbon: '8',
  Ibiza: '9',
  IbizaC: '9',
  Lima: '9 Baroless',
  Amsterdam: 'Spartan Ultra',
  Brighton: 'Spartan Sport',
  Cairo: 'Spartan WHR',
  Forssa: 'Spartan Trainer',
  Gdansk: 'Spartan WHR Baro',
  'Spartan Sport Wrist HR Baro': 'Spartan WHR Baro',
  Helsinki: '3 Fitness',
  'Ambit3 Sport': 'Ambit3 Sport',
  'Ambit3 Peak': 'Ambit3 Peak',
  'Ambit3 Run': 'Ambit3 Run',
  'Ambit3 Vertical': 'Ambit3 Vertical'
};
