/**
 * This enum works like a all matchers for normalized lap types between different naming across services
 */
export declare enum LapTypes {
    'unknown' = "Unknown",
    'Unknown' = "Unknown",
    'Start' = "Start",
    'start' = "Start",
    'Stop' = "Stop",
    'stop' = "Stop",
    'Manual' = "Manual",
    'manual' = "Manual",
    'Autolap' = "Auto lap",
    'AutoLap' = "Auto lap",
    'autolap' = "Auto lap",
    'Distance' = "Distance",
    'distance' = "Distance",
    'Location' = "Location",
    'location' = "Location",
    'interval' = "Interval",
    'Interval' = "Interval",
    'Time' = "Time",
    'time' = "Time",
    'HeartRate' = "Heart Rate",
    'Heart Rate' = "Heart Rate",
    'position_start' = "Position start",
    'Position start' = "Position start",
    'position_lap' = "Position lap",
    'Position lap' = "Position lap",
    'position_waypoint' = "Position waypoint",
    'Position waypoint' = "Position waypoint",
    'position_marked' = "Position marked",
    'Position marked' = "Position marked",
    'session_end' = "Session end",
    'Session end' = "Session end",
    'fitness_equipment' = "Fitness equipment",
    'itness equipment' = "Fitness equipment"
}
