"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImporterSuuntoDeviceNames = {
    'Athens': 'Suunto 0',
    'Paris': 'Suunto 1',
    'Berlin': 'Suunto 2',
    'Tokyo': 'Suunto 3',
    'Rome': 'Suunto 4',
    'Barcelona': 'Suunto 5',
    'Moscow': 'Suunto 6',
    'London': 'Suunto 7',
    'Lisbon': 'Suunto 8',
    'Ibiza': 'Suunto 9',
    'Lima': 'Suunto 9 Baroless',
    'Amsterdam': 'Suunto Spartan Ultra',
    'Brighton': 'Suunto Spartan Sport',
    'Cairo': 'Suunto Spartan WHR',
    'Forssa': 'Suunto Spartan Trainer',
    'Gdansk': 'Suunto Spartan WHR Baro',
    'Suunto Spartan Sport Wrist HR Baro': 'Suunto Spartan WHR Baro',
    'Helsinki': 'Suunto 3 Fitness',
    'Suunto Ambit3 Sport': 'Suunto Ambit3 Sport',
    'Suunto Ambit3 Peak': 'Suunto Ambit3 Peak',
    'Suunto Ambit3 Run': 'Suunto Ambit3 Run',
    'Suunto Ambit3 Vertical': 'Suunto Ambit3 Vertical',
};
